# $Id$

CONTIKI_TARGET_SOURCEFILES += contiki-sky-platform.c \
	sht11.c sht11-sensor.c light-sensor.c battery-sensor.c \
	button-sensor.c radio-sensor.c

include $(CONTIKI)/platform/sky/Makefile.common
