#
# Makefile for hexameter
# @author Takahide Matsutsuka <markn@markn.org>
#
# $Id$
#

CFLAGS =
SOURCEDIR = src
TARGET = hexameter.o ihx2bin.o

vpath %.c $(SOURCEDIR)

hexameter: $(TARGET)

clean:
	rm -f *.o *~ hexameter.exe
